### ISSUE TITLE
Replace "Mapping Spring's health indicators to metrics"

### ISSUE THREAD

**Issue by philwebb** [micrometer-metrics/micrometer-docs#127]
The [Mapping Spring's health indicators to metrics](http://micrometer.io/docs/guide/healthAsGauge) documentation is out of date. 

I've just fixed https://github.com/spring-projects/spring-boot/issues/18329 so as of Spring Boot 2.1.14 you can reference our how-to instead (https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-map-health-indicators-to-metrics).

**Comment by shakuzen** [comment]
Thanks for adding the Boot docs. We already have a link to Spring Boot documentation under the Reference section. I think we'll defer to that and delete our guide from the Micrometer site as @izeye has proposed in #126 rather than leave it with just a link to the section of the Spring Boot documentation.
