### ISSUE TITLE
Clarify metrics output for LongTaskTimer

### ISSUE THREAD

**Issue by haseeb-gh** [micrometer-metrics/micrometer-docs#179]
**Describe the bug**
When registry.close() is called before the step interval completes, LongTaskTimer sends inaccurate duration to InfluxDB.

**Environment**
 - Micrometer version 1.7.1
 - Micrometer registry InfluxDB 2.0.7
 - OS: Windows 10 Pro 1909
 - Java version: 1.8

**To Reproduce**
How to reproduce the bug:

```
public void reproduceIssue() {
    InfluxMeterRegistry registry = new InfluxMeterRegistry(influxConfig, Clock.SYSTEM); // step = Duration.ofSeconds(30)

    registry.more().longTaskTimer("dd-longtimer").record(() -> {
        registry.timer("dd-timer").record(() -> sleepThread(1000 * 25)); // sleep for 25 secs
    });

    registry.close(); // publish all metrics and close all resources.
}
```

**Expected behavior**
dd-longtimer should have a duration value greater than or equal to either 25k (25,000 milliseconds) or value of dd-timer metric. Instead dd-longtimer sends out duration which always less than dd-timer (observed results were in the range of 13k to 20k).

**Comment by shakuzen** [comment]
> Can something be done so no one else has to go through all of this?

Absolutely. I am sorry this was a pain for you, but indeed, let's improve the documentation so it is more clear for others. I've transferred the issue to the docs repository. Here is the current documentation on long task timers: https://micrometer.io/docs/concepts#_long_task_timers
If you have any specific suggestions, let us know or send a pull request to this repo with improvements. Otherwise, I will try to propose something to make it more clear.

**Comment by haseeb-gh** [comment]
Thank you @shakuzen. Please do go ahead and make a decision as to how the documentation should be updated to remove any sort of confusion. The goal being that documentation should mention that long task timers will stop providing metrics once they finish.
