### ISSUE TITLE
W3C link checker & curl show 404 while browser works

### ISSUE THREAD

**Issue by dreis2211** [micrometer-metrics/micrometer-docs#239]
Hi,

I was checking a documentation the other day with https://validator.w3.org/checklink that shows 404s basically for every micrometer doc URL that said documentation contains.

![image](https://user-images.githubusercontent.com/6304496/181632370-ed85d4f4-7953-46fa-86a4-e6fb3bbcd050.png)

The same can be reproduced by simply executing a curl command like the following:
```
curl -I https://micrometer.io/docs/registry/appOptics
HTTP/2 404
...
```

The exact same URLs work just fine inside a browser.

Maybe you can take a look to improve this and properly return 2xx status codes.

Cheers,
Christoph

**Comment by shakuzen** [comment]
Thank you for reporting this.
This is due to [this issue](https://create-react-app.dev/docs/deployment/#notes-on-client-side-routing) mentioned in #200 when we moved to GitHub Pages for hosting. We opted for the solution described as "a trick to teach GitHub Pages to handle 404s by redirecting to your `index.html` page with a custom redirect parameter." We could go with the other option to change how routing is performed to fix the issue you've described. But I believe this would create another issue of changing existing URLs which would break any documentation linking to them. That seems like a much bigger issue.

Given that, I'm not sure how urgent it is to fix this unless we can fix it in a different way that maintains existing URLs. Suggestions and/or pull requests would be welcome.

**Comment by dreis2211** [comment]
Not at all urgent. Just annoying to get these false positives on automated toolings like the W3C link checker.

**Comment by jonatan-ivanov** [comment]
We upgraded the site, this should be fixed, https://validator.w3.org/checklink seems to be mostly happy too.

**Comment by chalin** [comment]
Thanks. FYI, I'm still getting 404s:

```console
$ curl -sI https://micrometer.io/docs/tracing#_micrometer_tracing_opentelemetry_setup | grep HTTP
HTTP/2 404 
```

**Comment by shakuzen** [comment]
That link is for the old, archived docs. When visiting it in a web browser you should see at the top a banner that says the following with a link to [the latest docs](https://docs.micrometer.io/micrometer/reference/):

> This is an archive to keep links alive.
